### ISSUE TITLE
binary data type

### ISSUE THREAD

**Issue by usergoodvery** [babelouest/hoel#11]
Hi
I have a binary column in my mysql db of a fixed length. Does this library support updating and querying that filed? will data be retained in original binary, or encoding is necessary?

regards

**Comment by babelouest** [comment]
Depending on your data and how you access it, there are several options.

# Binary column with printable characters

If you store only printable characters in this column, hoel will handle it without any problem. I'm using the tinyblob or mediumblob to store either base64 strings or json data.
In that case, if you use the json-based language to build your queries, the result will be returned in a json string.

I used to use this method to store images thumbnails or even full-size images in a sqlite or mariadb database with [Taliesin](https://github.com/babelouest/taliesin) at first. After realizing that the performance were dropping because of the images size I stopped using it.
But I still use base64 encoded medium blobs in [Hutch](https://github.com/babelouest/hutch) without any problem.

# Binary column with no printable characters

This case has 2 different options:
- either you use the `struct _h_result`, and in that case the blob type called `struct _h_type_blob` will store your binary data, nothing special to change in your code.
- either you use the json-based query language, and in that case you'll need to encode/decode as base64 for example because JSON data only accepts utf8 characters.

On the second case, you'll have to build your queries with something like:

```C
// Select binary column
json_t * j_query_select = json_pack("{sss[s]}", "table", "my_table", "columns", "TO_BASE64(`my_binary_column`)"), * j_result_select;
if (h_select(conn, j_query_select, &j_result_select, NULL) == H_OK) {
  printf("Select result base64 encoded is %s\n", json_dumps(j_result_select));
}

// insert binary column with the value stored in the char * variable my_binary_value_encoded
char * value = msprintf("FROM_BASE64('%s')", my_binary_value_encoded);
json_t * j_query_insert = json_pack("{sss{ss}}", "table", "my_table", "values", "my_binary_column", value);
if (h_insert(conn, j_query, NULL) == H_OK) {
  printf("Insert binary value OK\n");
}
```

**Comment by usergoodvery** [comment]
Thanks for sharing your thoughts. In my case I'd be storing and retrieving non printable binary. I have seen the struct _h_type_blob which will be fine for retrieving raw binary, because it specify length which is fine. But how do you insert/update raw, unencoded?

**Comment by babelouest** [comment]
For now you can use the `struct _h_type_blob` and derivatives as a result of a select statement only. You can't use in an insert or update, sorry.

If your data is raw binary (i.e. a set of `0` and `1`), are the built-in binary functions in MySQL not enough for your needs?

I'd have to think of a clean design but maybe it could be added in a future release.

**Comment by usergoodvery** [comment]
my buffer is not  necessarily  0  and 1; just arbitrary bytes
The approach I am considering (which I don't find too elegant, but does the job) is to convert the buffer to hex representation and use mysql's unhex() on the insert side to convert to binary  storage

**Comment by babelouest** [comment]
I agree

I'm thinking of new features to facilitate this.

When you use `struct _h_result` data, you need to build the sql query by hand and pass it to the dedicated functions: `h_query_select`, `h_query_insert`, `h_query_update` or `h_query_delete`.
In the case of `h_query_select` you get the result in a `struct _h_result`.

What if you had a new kind of `h_query_update` called `h_query_update_result` for example, in which you pass a `struct _h_result` as a parameter and hoel does the update for you? Same goes for insert, or delete.

I'd have to add a flag to the `struct _h_data` to identify primary keys.

It would be like an ORM but very low level, without the objects structure and behaviour, and it would work on only one table, not on imbricated data on multiple tables.

**Comment by usergoodvery** [comment]
I'd take cues from how hiredis (redis's c api)  build its query string, which is modeled after standard printf with a %b for binary (in which which case user has to also specify length). Your underlying buffer should be binary friendly of course. I think that will work with existing design without major redesign.

Your design idea is also interesting, to the extent I understood it, it appears similar to how sqlite builds its query string (referring to java implementation) by expecting the user to pass array of   key-value pairs and it builds the final query off that.

**Comment by babelouest** [comment]
The hiredis approach is interesting, I could take ideas from there, thanks.

But my design idea requires a lot of work and I already have a huge todo list before I can get to it (implementing insert/update/delete with `struct _h_data`).
Before that, I'm looking for a quick win for you.

Is it possible for you to encode/decode using base64 with the json query? You can use any base64 library you want, or use [orcania's functions](https://github.com/babelouest/orcania/blob/master/include/orcania.h#L237), orcania is required by hoel so you already have it installed.

You have a table with data and you want to manipulate it as binary, you could go like this:

```C
#define COLUMN_LEN 42

// Select in table, convert binary to base64
json_t * j_query = json_pack("{sss[ss]}",
                   "table",
                   "my_table"
                   "columns",
                     "my_id",
                     "TO_BASE64(`my_binary_column`) AS my_binary_column");
       * j_result = NULL,
       * j_value,
       * j_query_update;
unsigned char decoded_data[COLUMN_LEN], * encoded_data[COLUMN_LEN * 2];
char * str_data, * my_binary_column_subquery;
size_t data_size, index;

if (h_select(conn, j_query, &j_result, NULL) == H_OK) {
  json_foreach(j_result, index, j_value) {
    str_data = json_string_value(json_object_get(j_value, "my_binary_column"));
    if (o_base64_decode(str_data, o_strlen(str_data), decoded_data, &data_size)) {
      // do something with decoded_data
      
      // update table
      if (o_base64_encode(decoded_data, COLUMN_LEN, encoded_data, &data_size)) {
        my_binary_column_subquery = msprintf("FROM_BASE64('%s')", encoded_data);
        j_query_update = json_pack("{sss{sOs{ss}}}",
                         "table",
                         "my_table",
                           "values",
                             "my_id",
                             json_object_get(j_value, "my_id"),
                             "my_binary_column",
                               "raw",
                               my_binary_column_subquery);
        o_free(my_binary_column_subquery);
        if (h_update(conn, j_query_update, NULL) == H_OK) {
          // Update OK
        } else {
          // Update error
        }
        json_decref(j_query_update);
      }
    }
  }
}

json_decref(j_result);
json_decref(j_query);
```

You must link orcania to your program by adding the flag `-lorcania`.

**Comment by usergoodvery** [comment]
json is an option I looked at initially but processing overhead was an issue, plus this won't allow me to store native binary, which increases storage requirement on the db side. 
The approach I have adopted with unhex() works fine for the time being, so I am happy to revisit this one when you are ready with your new redesign.

**Comment by usergoodvery** [comment]
interestingly, the library reports the binary field type as text (type 2) as opposed to blob. I was wondering if you have been able to correctly retrieve data stored as binary? (my mysql type is binary(16))

**Comment by usergoodvery** [comment]
OK I figured out where the problem is. Since the connector is reporting the field as text, that tricks your code into doing ((struct _h_type_text *)data->t_data)->value = malloc(strlen(value)+sizeof(char)); and the subsequent strncpy(), which of course doesn't work with binary data.

However, as you are actually reading off the size as in h_get_mariadb_value (value=0x7fffe00434fc "\357\223\001\202\215\222b\020\266\001", length=16, m_type=254), I ended up replacing strlen(value)+sizeof(char) with the value of length if >0 and replaced strncpy with memcpy

These are some of struct member values from mysql (field)
length = 16,
  max_length = 16,
  name_length = 8,
  org_name_length = 8,
  table_length = 8,
  org_table_length = 8,
  db_length = 5,
  catalog_length = 3,
  def_length = 0,
  flags = 16516,
  decimals = 0,
  charsetnr = 63,
  type = MYSQL_TYPE_STRING,
  extension = 0x0

**Comment by babelouest** [comment]
Hello @usergoodvery ,

Indeed, one of the problem was that mysql considers a binary as a text: `m_type = 254`.
And another problem was that I used `strlen` to guess the size of the value for text types, therefore, in your case, the behaviour was `undefined`...

I've used your advice and created a branch to fix this issue.
Can you checkout the branch `binary-fix` to see if your problem is fixed?

**Comment by usergoodvery** [comment]
In order to fix this at working code level I had to add a size_t member to struct _h_type_text, then modified the following two functions to operate on the returned data, retaining the actual size of the binary buffer
h_new_data_text ()
h_row_add_data()

**Comment by babelouest** [comment]
My bad, I forgot to commit the changes in the library...

Please check the branch [binary-fix](https://github.com/babelouest/hoel/tree/binary-fix)

The `struct _h_type_text` now has a property `size_t length`.
When hoel is getting a text field, it nows uses `memcpy` and no more `strlen` or `strncpy`.
Although, to make sure the `struct _h_type_text.value` is a correct string, hoel adds a `\0` character at the end of the `value`.

You can check the [last commit](https://github.com/babelouest/hoel/commit/bcb0c04c01b886715ab7a4f252f5fc0713f20d18) in `binary-fix` for the details.

**Comment by usergoodvery** [comment]
great I think what you did there does the trick

**Comment by babelouest** [comment]
Great, I'll merge in master branch then.

**Comment by babelouest** [comment]
@usergoodvery , I call from this old issue to ask you a question about the change I made at your request.
I got a bug on text values recently.

I had a problem in Glewlwyd due to empty colums of type text (varchar) that returned NULL values. The problems lies [here](https://github.com/babelouest/hoel/blob/master/src/hoel-mariadb.c#L394)

The fix simply says that if a text column is empty, the `_h_data` returned is an empty string instead of a NULL value. Will this fit in your workflow? You'll still have length value set to 0 though.
