### ISSUE TITLE
type narrowing bug

### ISSUE THREAD

**Issue by usergoodvery** [babelouest/hoel#15]
Hi 
I noticed in your implementation of mariadb you are down casting quite few types to _int_ as you fetch INT, LONG etc.., therefore resulting in data loss when this fetched value is reassigned to a bigger type. This happens in function _h_get_mariadb_value(const char * value, const unsigned long length, const int m_type)_ namely the line:

``
i_value = strtol(value, &endptr, 10);
``
i_value should be declared minimum int64_t (or largest available) and the struct _h_type_int should be augmented as well, or expand the pool of available types

**Comment by babelouest** [comment]
Hello @usergoodvery ,

You're right, `struct _h_type_int` should host a larger integer than the regular `int`.

My idea is that I should use `long long int` and `strtoll` instead of `int` and `strtol`. Not that I don't like `int64_t` but `strtoll` returns a `long long int`, so it would be more intuitive.

What do you think?

**Comment by usergoodvery** [comment]
sure it is your call. long long int would also cover u_int64 if I recall, which is even wider coverage.
 I suggest you also update the the last inserted id code as well, as that returns int.

**Comment by babelouest** [comment]
@usergoodvery , `struct _h_type_int` and return type of `h_last_insert_id_*` int size has enlarged in https://github.com/babelouest/hoel/commit/f3aa1e2e40224bcdc647b989e36463e1a0fcfae3 
Let me know if you find other issues.

**Comment by usergoodvery** [comment]
good stuff looks good thanks
