### ISSUE TITLE
SQLite3 Blob types are considered Text by hoel

### ISSUE THREAD

**Issue by Spacefreak18** [babelouest/hoel#22]
this can be recreated with the example_sqlite3.c.

Just add a blob column to example_sqlite3.sql, add some data to it in the example_sqlite3.c, and you will see the blob column will fall into the text type in the switch statement.

I did this on my local, i can put it in a quick fork if that's helpful.

`
  query = msprintf("insert into %s (name, age, temperature, blah) values ('%s', %d, %f, hex('%s'))", table, sanitized, 33, 37.2, "DEADBEEF");
`

`
CREATE TABLE other_test (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    age INTEGER,
    temperature FLOAT,
    blah BLOB
);
`

this isn't really a pressing issue for me because where i came across this in my project, i didn't need different text and binary columns that were handled differently

**Comment by babelouest** [comment]
Hello @Spacefreak18 ,

I think the problem is how SQLite3 handles binary data vs strings.  If I understand [SQLite3 data types](https://www.sqlite.org/datatype3.html), a `TEXT` and a `BLOB` are similar in storage.

In your example, you insert `hex('DEADBEEF')` as a blob, but this returns a string. In SQLite3, a hex value has the form `x'1234'`.
Therefore, if you change your query to this one:

```C
query = msprintf("insert into %s (name, age, temperature, blah) values ('%s', %d, %f, %s)", table, sanitized, 33, 37.2, "x'DEADBEEF'");
```

Then the value will be stored and retrieved as blob.

Nevertheless, there's a bug in the `print_result` function in the example file, the `printf` for a blob byte must be a hex print:

```C
printf("%02x", *((char*)(((struct _h_type_blob *)result.data[row][col].t_data)->value+i)));
```

Then, the output result will be: `| 66 | Hodor | 33 | 37.200000 | 0xffffffdeffffffadffffffbeffffffef |`

Although, note that this project is in deep sleep state, because I don't have anymore time to work on it. Don't expect heavy support or new features.

**Comment by Spacefreak18** [comment]
yes, i saw that text and blob were similar in storage as you mentioned, i figured that's why this was happening.

and i also meant to do unhex, that's where my mistake was. shoot.

And don't worry, i think it's pretty solid as is :) That's the beauty of C, the whole world isn't going to change underneath you like it does with something like Python.
